version: 2.1
jobs:
 build:
   machine: true
   steps:
     ## install more recent version of docker-compose
     - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     - run: sudo chmod a+x /usr/local/bin/docker-compose

     ## build container
     - checkout
     - run: cd ./docker && docker-compose up

     ## after having pseudo secrets, there should be a clone
     - run: docker-compose up
