# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:
        machine: true
        steps:

          ## install more recent version of docker-compose
          - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - run: sudo chmod a+x /usr/local/bin/docker-compose

          ## build container
          - checkout
          - run: cd ./docker && docker-compose up

          ## after having pseudo secrets, there should be a clone
          - run: docker-compose up
