version: 2.1
jobs:
 build:
   machine: true
   steps:
     ## tools
     - run: sudo apt-get install -y libffi-dev libssl-dev python3-dev python3 python3-pip
     - run: pip3 install docker-compose

     ## sources
     - checkout

     ## build container
     - run: ./setup.sh ci
