version: 2.1
jobs:
 build:
   machine: true
   steps:
     ## tools
     #- run: sudo apt-get install -y libffi-dev libssl-dev python3-dev python3 python3-pip
     #- run: pip3 install docker-compose
     ## circleci seems to have issues with signatures
     - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     - run: sudo chmod a+x /usr/local/bin/docker-compose

     ## sources
     - checkout

     ## build container
     - run: ./setup.sh ci
