version: '3.8'

services:
    u-boot_devel:
        container_name: u-boot
        image: rubuschl/u-boot
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"  ## docker run --user=$USER
        working_dir: /home/$USER ## docker run --workdir=...
        stdin_open: true         ## docker run -i
        tty: true                ## docker run -t
        hostname: u-boot_devel
        #privileged: true
        environment:
          - USER
        env_file:
          - .env
        volumes:
          ## folders not need to be around
          - ./u-boot:/home/$USER/u-boot
          - ./secrets:/home/$USER/secrets
          - ./workspace:/home/$USER/workspace
          - ./workspace.opt:/opt
          ## folder must be around
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
